// enum
// {
    // RENDER_THREAD_COUNT_MAX = 1,

    // RENDER_FRAME_OVERLAP = 3,
    // RENDER_FRAME_ARENA_SIZE = DOT_KB(32),

    // RENDERER_BACKEND_TRANSIENT_MEM_SIZE  = DOT_KB(512),

    // RENDER_TEXURE_MAX = 512,
    // RENDER_BUFFER_MAX = 4096,
    // RENDER_SAMPLER_MAX = 128,

    // RENDER_COMMAND_BUFFERS_PER_POOL = 4 * RENDER_THREAD_COUNT_MAX,

    // RENDER_COMMAND_POOLS_PER_MAX = RENDER_SWAPCHAIN_TEXTURES_MAX * RENDER_THREAD_COUNT_MAX,

    // RENDER_CTX_RESCOURCE_POOL = 128,
    // RENDER_RESOURCE_CLEANUP_CTX_TEXTURES  = 24,
    // RENDER_RESOURCE_CLEANUP_CTX_BUFFERS   = 24,
    // RENDER_RESOURCE_CLEANUP_CTX_SAMPLERS  = 24,

    // RENDER_BACKEND_ALLOC_SIZE =
    //     (RENDER_CTX_RESCOURCE_POOL * RENDER_RESOURCE_CLEANUP_CTX_TEXTURES * RENDER_RESOURCE_CLEANUP_CTX_BUFFERS * RENDER_RESOURCE_CLEANUP_CTX_SAMPLERS * sizeof(PoolHandle)),

    // RENDERER_BACKEND_MEM_SIZE            = DOT_KB(512)
    //         + RENDER_BACKEND_ALLOC_SIZE
    //         + RENDERER_BACKEND_TRANSIENT_MEM_SIZE,
        // (jd) RENDER_Texture isn't yet included here, maybe we need to make render_backend_vk_types
        // + RENDER_TEXURE_MAX * sizeof(RENDER_Texture)
        // + RENDER_BUFFER_MAX * sizeof(RENDER_Buffer)
        // + RENDER_SAMPLER_MAX * sizeof(RENDER_Sampler)
// };
